name: Build

on:
  push:
    branches:
      - main


jobs:


  tests:
    name: Run tests and Scan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: Run tests
        run: go test -coverprofile=coverage.out ./...

      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v4

